USE [SmartERP.Database]
GO
IF NOT EXISTS( SELECT TOP 1 * FROM MENU) 
BEGIN 

INSERT [dbo].[RoleGroup] ([RoleGroupName], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Finance', GETDATE(), GETDATE(), N'admin', N'admin', 1)

INSERT [dbo].[Role] ([RoleName], [BaseControl], [RoleGroupCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'HO Admin', N'B', 1, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Role] ([RoleName], [BaseControl], [RoleGroupCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Branch Manager', N'B', 1, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Role] ([RoleName], [BaseControl], [RoleGroupCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Branch Operations', N'B', 1, GETDATE(), GETDATE(), N'admin', N'admin', 1)

INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Dashboard', N'', 0, N'Module', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Application Settings', N'', 0, N'Module', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Sales Configuration', N'', 0, N'Module', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Sales Transaction', N'', 0, N'Module', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Sales Reports', N'', 0, N'Module', GETDATE(), GETDATE(), N'admin', N'admin', 1)

INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Stock Dashboard', N'home,index', 1, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Accounts Dashboard', N'home,index', 1, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Sales Dashboard', N'home,index', 1, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Service Dashboard', N'home,index', 1, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)

INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Security Policy', N'misc,privacypolicy', 2, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Manage User', N'account,users', 2, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'User Roles & Rights', N'misc,roles', 2, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Unlock User Account', N'account,unlockusers', 2, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)

INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Company', N'configuration,companies', 3, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Business Center', N'businesslocation,businesscenters', 3, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Tax Structure', N'', 3, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Product Trade Discount', N'', 3, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Branch Controls', N'', 3, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'DealerControls', N'', 3, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Dealer Flexi Trade Discount', N'', 3, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)

INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Order Policy', N'', 4, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Discount Policy', N'', 4, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Priority & Allocation', N'', 4, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Invoice', N'', 4, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'EOD Process', N'', 4, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)

INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Print Invoice', N'', 5, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Trade Discount', N'', 5, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[Menu] ( [MenuName], [MenuURL], [ParentMenucode], [MenuType], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (N'Dealer Flexi Trade Discount', N'', 5, N'Menu', GETDATE(), GETDATE(), N'admin', N'admin', 1)


INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 1, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 2, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 3, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 4, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 5, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 6, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 7, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 8, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 9, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 10, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 11, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 12, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 13, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 14, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 15, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 16, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 17, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 18, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 19, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 20, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 21, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 22, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 23, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 24, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 25, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 26, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 27, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (1, 28, GETDATE(), GETDATE(), N'admin', N'admin', 1)

INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 1, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 3, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 4, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 5, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 6, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 7, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 8, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 9, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 18, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 19, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 20, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 23, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 24, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 25, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 26, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 27, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (2, 28, GETDATE(), GETDATE(), N'admin', N'admin', 1)


INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (3, 1, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (3, 4, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (3, 5, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (3, 6, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (3, 7, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (3, 8, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (3, 9, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (3, 24, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (3, 26, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (3, 27, GETDATE(), GETDATE(), N'admin', N'admin', 1)
INSERT [dbo].[RoleMenu] ([RoleCode], [MenuCode], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (3, 28, GETDATE(), GETDATE(), N'admin', N'admin', 1)

INSERT [dbo].[Security] ([MinLength], [MaxLength], [ExpiryDays], [LockoutCount], [SessionTimeoutWorkforce], [SessionTimeoutOthers], [IsAlphaMust], [IsNumericMust], [IsSplCharMust], [IsFirstPwdChange], [IsVirtualKeyboard], [IsIpRestricted], [IsCaptchaRequired], [IsForgotPassword], [IsCloseBrowser], [IsAutoLogout], [IpAddress], [RemoteAccess], [CreatedTimeStamp], [UpdatedTimeStamp], [CreatedBy], [UpdatedBy], [IsActive]) VALUES (8, 16, 60, 5, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, N'123.23.21.24', N'2', GETDATE(), GETDATE(), NULL, NULL, 0)

END